-- 코드를 입력하세요
# SELECT count(*), (p.PRICE * o.SALES_AMOUNT) as SALES
# select * 
# FROM PRODUCT p
# JOIN OFFLINE_SALE o
# ON p.PRODUCT_ID = o.PRODUCT_ID
# GROUP BY p.PRODUCT_ID
# ORDER BY SALES DESC, p.PRODUCT_CODE ASC;

select PRODUCT_CODE, sum(p.PRICE * o.SALES_AMOUNT) as SALES
FROM PRODUCT p
JOIN OFFLINE_SALE o
ON p.PRODUCT_ID = o.PRODUCT_ID
GROUP BY PRODUCT_CODE
ORDER BY SALES DESC, PRODUCT_CODE ASC;