SELECT I.REST_ID, I.REST_NAME, I.FOOD_TYPE, I.FAVORITES, I.ADDRESS, ROUND(AVG(REVIEW_SCORE),2) AS AVERAGE
FROM REST_INFO I
JOIN REST_REVIEW R
ON I.REST_ID = R.REST_ID
GROUP BY REST_ID
HAVING ADDRESS LIKE '서울%'
ORDER BY AVERAGE DESC, I.FAVORITES DESC

